# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TutoringApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TutoringApp
  pod 'Parse'
  pod 'AlamofireImage'

  target 'TutoringAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TutoringAppUITests' do
    # Pods for testing
  end

end
